#!/bin/bash

# Required to expand aliases (so bximake is known)
#shopt -s expand_aliases
#source /mnt/hpcbxi/bxienv -r /tmp
#BXI_PDP_MODE="true" RPM_INSTALL_OPT="--relocate /etc=/tmp/etc --relocate /usr=/tmp/usr" make --jobs --no-print-directory --directory /mnt/hpcbxi $1.pdp 
# Hack to prevent top_build_subdir error during rpm generation (Ask John if you don't get why! ;-))
export BXI_BUILD_SUBDIR="/"
TMPDIR=$(mktemp -d docker-pdp.mkrpm.XXX)
cd ${TMPDIR}
/mnt/configure && make --jobs --no-print-directory rpm
#BXI_PDP_MODE="false" make --jobs --no-print-directory --directory /mnt/hpcbxi $1.rpm 

#&& \ su -c "createrepo --update /rpms && yum clean metadata && yum -y install $1-devel"

